# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            idea note
tagline:          'defying loss of memory'
description:      'blah blah blah'
url:              http://aichaku.github.io

author:
  name:           'Dongwoo Lee'
  url:            https://www.facebook.com/aichaku

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/aichaku
